name: Frogbot Scan and Fix

on:
  pull_request_target: 
    types: [opened, synchronize] 
  push: 
    branches:
      - v1
  schedule:
    - cron: "25 * * * *"  
  workflow_dispatch: 

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main", "v1"]
    steps:
      - uses: jfrog/frogbot@v2
        with:
          oidc-provider-name: ${{ secrets.OIDC_PROVIDER_NAME }}
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}