name: Workflow-Task-seed
on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag'
        required: false
        default: 'v1'
        type: string

permissions:
  actions: read
  id-token: write
  packages: write
  security-events: write
  attestations: write
  contents: read

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.JFROG_DOCKER_REPO }}
      IMAGE_NAME: myApp
      JF_URL: ${{ secrets.JFROG_REGISTRY_URL }}
      NPM_VIRTUAL_REPO: ${{ vars.NPM_VIRTUAL_REPO }}
      DOCKER_BUILD_SUMMARY: false
      DOCKER_BUILD_RECORD_UPLOAD: false
      JFROG_CLI_LOG_LEVEL: DEBUG
      IMAGE_TAG: ${{ github.event.inputs.docker_tag }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        oidc-provider-name: ${{ secrets.OIDC_PROVIDER_NAME }}
        oidc-audience: repo:eladpl97/jfrog_task:ref:refs/heads/*

    - name: Set CLI Config
      run: jf npm-config --global=true --repo-resolve=${{ env.NPM_VIRTUAL_REPO }} --repo-deploy=${{ env.NPM_VIRTUAL_REPO }}

    - name: Build webapp
      run: jf npm ci

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate Docker
      uses: docker/login-action@v3
      with:
        registry: ${{ env.JF_URL }}
        username: ${{ steps.setup-cli.outputs.oidc-user }}
        password: ${{ steps.setup-cli.outputs.oidc-token }}

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      id: build
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        provenance: false

    - name: Add docker package to build info
      run: |
        echo "${{ env.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}@${{ steps.build.outputs.digest }}" > metadata.json
        jf rt build-docker-create ${{ env.DOCKER_REPO }} --image-file metadata.json

    - name: Publish build info
      run: |
        jf rt build-collect-env
        jf rt build-add-git
        jf rt build-publish
